### ISSUE TITLE
Use entity resolution service to resolve grants to determine uniqueness

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-entity-resolver#13]
Given id and agency?
Create the URI using the agency and id.

spo # is unique grant number (external to SeRA, i.e. it is the identifier in the grantees system) that should also be in some WoS data

blocked by sul-dlss/rialto#284

**Comment by peetucket** [comment]
consider if resolution is even necessary given that we should be able to look up a unique ID present in each grant record
