### ISSUE TITLE
Write entities to specific named graphs?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-entity-resolver#21]
The ETL writes to different named graph for different sources, should this also write to named graphs?  If so which ones?

**Comment by mjgiarlo** [comment]
Question for tomorrow's architecture check-in?

**Comment by jcoyne** [comment]
Yes, it's on the agenda there.

**Comment by jcoyne** [comment]
Move to rialto-etl

**Comment by justinlittman** [comment]
The organization and people transformers do write to named graph. I will add to WOS transformer. (All it requires is `@graph` and the SparqlStatementWriter will handle.)

**Comment by jcoyne** [comment]
@justinlittman this was about the entity-resolver, not the etl.
